### ISSUE TITLE
Autogen docs for climake

### ISSUE THREAD

**Issue by tristan-zander** [rust-cli/climake#10]
I found this project recently that could really help me with another project that I'm taking a break on. I'd like to contribute this to the v3-remake branch and would be open to helping with other parts.

Information on how the commands are supposed to be used in the CLI is already contained in the structs, so documentation can be automated through a macro. 
### Example Usage
```rust
#[document_args] // Will be replaced by content similar to `cli help` based on the usage in `fn main()`
fn main() {
    let args = Argument::new(...);
    let cli = CliMake::new(...);
}
```
I'm not quite sure if macros can be expanded before publishing crates but I think the same sort of behavior can be achieved through a build script. I know that this could be used to generate `man` pages through other crates but you'd have to introduce dependencies. Let me know if you approve of this or you want help with other things.

Update: Macros are expanded before rustdocs are made. It's simple to evaluate the args within the Tokenstream and then just prepend `///` before every line

**Comment by Owez** [comment]
What would be the use of adding CLI help to the `main` func (or other functions which contain climake) apart from generation of manpages? Some sort of `## Usage`-like heading?

(Apologies for the late reply, exam week in school)

**Comment by tristan-zander** [comment]
I think that adding automatic documentation features would just make climake applications easy to use from a user's standpoint. The documentation is already generated whenever someone calls `--help`, so it's as easy as tagging the custom CliMake struct, main function, or whole crate as #[doc_args], parsing any CliMake structs, calling the usage function, and then formatting it to Rust documentation standards. That's probably like 10 - 20 lines of code since you've already written the usage function in master.

This is kind of a niche thing and the more I thought about it the less it made sense unless I'd make it automatically generate man pages or update README.md for users to read right there. Man page generation would be really nice but the crate's goal is to be dependency-less (if I'm reading it right). I think that my enthusiasm to start committing to open source might just be a little too high unless you feel like this would be used in any more than my projects.

**Comment by Owez** [comment]
I think right now I'll leave it as the user already has full control of the library using public `cli.help_msg()`-like functions that will generate any help they'd like to automatically add. Man-pages could be very useful though the help messaging may need to be redone further or have 2 separate help message variants, one for cli help and one for man-pages.

Currently it's more beneficial to get the MVP of the rewrite out and figure out a nicer help system for edge cases like help msg character limits.

Currently I'm in the midst of exams unfortunately so I can't help contribute much to the rewrite so it might progress slow anyhow, apologies.

**Comment by tristan-zander** [comment]
No worries. If you'd like any help I'm always willing to do PRs but as for now I'll close this issue. Thanks for making this crate.
