### ISSUE TITLE
Required argument

### ISSUE THREAD

**Issue by 89z** [rust-cli/climake#11]
For my use case, I would need something like this:

~~~
program [options] <argument>
~~~

Where the argument is required, and the options are optional. It doesnt appear
this crate handles that use case. Is that correct?

**Comment by Owez** [comment]
Unfortunately the library current doesn't and you'll have to specify it yourself if the arg was not found. I'll add it as a feature for the `v3-rewrite` branch currently in progress which is slated for release in ~1-2 months

**Comment by 89z** [comment]
I found another option:

https://github.com/rust-lang/getopts

**Comment by Owez** [comment]
Added in 36b01fe, closing
